
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SCS
 */

import java.util.List;
import javax.swing.*;

public class ExpensesTrackerGUI extends javax.swing.JFrame {
    private ExpenseManager manager = new ExpenseManager(); //create an object from expense manager class
   
     /*Creates new form ExpensesTrackerGUI
     */
    public ExpensesTrackerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGRP = new javax.swing.ButtonGroup();
        SearchTabBG = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        viewExp = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        foodRB = new javax.swing.JRadioButton();
        billsRB = new javax.swing.JRadioButton();
        entertainmentRB = new javax.swing.JRadioButton();
        transportRB = new javax.swing.JRadioButton();
        groceriesRB = new javax.swing.JRadioButton();
        travelRB = new javax.swing.JRadioButton();
        othersRB = new javax.swing.JRadioButton();
        healthcareRB = new javax.swing.JRadioButton();
        shoppingRB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        descTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moneyOutTA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        viewTA = new javax.swing.JTextArea();
        summaryBTN = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        saveBTN = new javax.swing.JButton();
        searchEBTN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        editDateTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        editAmountTF = new javax.swing.JTextField();
        editCategoryTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        editDescTF = new javax.swing.JTextField();
        resetEBTN = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        foodRBS = new javax.swing.JRadioButton();
        billsRBS = new javax.swing.JRadioButton();
        entRBS = new javax.swing.JRadioButton();
        transportRBS = new javax.swing.JRadioButton();
        shoppingRBS = new javax.swing.JRadioButton();
        healthcareRBS = new javax.swing.JRadioButton();
        othersRBS = new javax.swing.JRadioButton();
        groceriesRBS = new javax.swing.JRadioButton();
        travelRBS = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordCTA = new javax.swing.JTextArea();
        searchSBTN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        totalCBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        totalCTA = new javax.swing.JTextArea();
        resetCBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        idDTF = new javax.swing.JTextField();
        deleteBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        setSize(new java.awt.Dimension(300, 300));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 1242));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Budget Buddy");

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        viewExp.setBackground(new java.awt.Color(255, 255, 255));
        viewExp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 102)));
        viewExp.setForeground(new java.awt.Color(204, 0, 51));
        viewExp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Amount:");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Date:");

        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter date in D/MM/YYYY format");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Category:");

        foodRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(foodRB);
        foodRB.setText("Food & Drink");

        billsRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(billsRB);
        billsRB.setText("Bills & Fees");
        billsRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsRBActionPerformed(evt);
            }
        });

        entertainmentRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(entertainmentRB);
        entertainmentRB.setText("Entertainment");

        transportRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(transportRB);
        transportRB.setText("Transport");
        transportRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportRBActionPerformed(evt);
            }
        });

        groceriesRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(groceriesRB);
        groceriesRB.setText("Groceries");

        travelRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(travelRB);
        travelRB.setText("Travel");

        othersRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(othersRB);
        othersRB.setText("Others");

        healthcareRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(healthcareRB);
        healthcareRB.setText("Healthcare");
        healthcareRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthcareRBActionPerformed(evt);
            }
        });

        shoppingRB.setBackground(new java.awt.Color(255, 204, 204));
        btnGRP.add(shoppingRB);
        shoppingRB.setText("Shopping");
        shoppingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingRBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Description:");

        addBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBTN.setForeground(new java.awt.Color(204, 0, 0));
        addBTN.setText("Add Expense");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        resetBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetBTN.setForeground(new java.awt.Color(204, 0, 0));
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(foodRB)
                                            .addComponent(billsRB)
                                            .addComponent(entertainmentRB))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(groceriesRB)
                                            .addComponent(travelRB)
                                            .addComponent(transportRB))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(othersRB)
                                            .addComponent(healthcareRB)
                                            .addComponent(shoppingRB)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(70, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descTF, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(145, 145, 145))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transportRB)
                            .addComponent(foodRB)
                            .addComponent(shoppingRB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groceriesRB)
                            .addComponent(billsRB)
                            .addComponent(healthcareRB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entertainmentRB)
                            .addComponent(travelRB)
                            .addComponent(othersRB))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBTN)
                    .addComponent(resetBTN))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        viewExp.addTab("Add Expense", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setForeground(new java.awt.Color(255, 102, 102));

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Added Expenses");

        moneyOutTA.setBackground(new java.awt.Color(255, 204, 204));
        moneyOutTA.setColumns(20);
        moneyOutTA.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        moneyOutTA.setRows(5);
        moneyOutTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(moneyOutTA);

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Money Out So Far");

        viewTA.setBackground(new java.awt.Color(255, 204, 204));
        viewTA.setColumns(20);
        viewTA.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        viewTA.setRows(5);
        viewTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewTA.setCaretColor(new java.awt.Color(255, 102, 102));
        jScrollPane5.setViewportView(viewTA);

        summaryBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        summaryBTN.setForeground(new java.awt.Color(204, 0, 0));
        summaryBTN.setText("Update This Page");
        summaryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(summaryBTN))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(summaryBTN)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        viewExp.addTab("View/Manage Expenses", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setForeground(new java.awt.Color(255, 204, 204));

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));
        jPanel10.setForeground(new java.awt.Color(255, 204, 204));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("ID to Edit:");

        saveBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(204, 0, 0));
        saveBTN.setText("Save Changes");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        searchEBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchEBTN.setForeground(new java.awt.Color(204, 0, 0));
        searchEBTN.setText("Search to Edit");
        searchEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEBTNActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Enter Details to Edit:");

        jPanel14.setBackground(new java.awt.Color(255, 204, 204));
        jPanel14.setForeground(new java.awt.Color(255, 204, 204));

        jLabel13.setText("Edit Date");

        jLabel16.setText("Edit Amount");

        jLabel14.setText("Edit Category");

        jLabel15.setText("Edit Description");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editCategoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(editDescTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(editAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editCategoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDescTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resetEBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetEBTN.setForeground(new java.awt.Color(204, 0, 0));
        resetEBTN.setText("Reset All");
        resetEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetEBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(searchEBTN))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(resetEBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveBTN)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEBTN)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBTN)
                            .addComponent(resetEBTN))
                        .addGap(211, 211, 211))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        viewExp.addTab("Edit Expenses", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));

        foodRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(foodRBS);
        foodRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        foodRBS.setForeground(new java.awt.Color(204, 0, 0));
        foodRBS.setText("Food & Drink");
        foodRBS.setBorder(null);

        billsRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(billsRBS);
        billsRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        billsRBS.setForeground(new java.awt.Color(204, 0, 0));
        billsRBS.setText("Bills & Fees");

        entRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(entRBS);
        entRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        entRBS.setForeground(new java.awt.Color(204, 0, 0));
        entRBS.setText("Entertainment");

        transportRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(transportRBS);
        transportRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        transportRBS.setForeground(new java.awt.Color(204, 0, 0));
        transportRBS.setText("Transport");

        shoppingRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(shoppingRBS);
        shoppingRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        shoppingRBS.setForeground(new java.awt.Color(204, 0, 0));
        shoppingRBS.setText("Shopping");

        healthcareRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(healthcareRBS);
        healthcareRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        healthcareRBS.setForeground(new java.awt.Color(204, 0, 0));
        healthcareRBS.setText("Healthcare");

        othersRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(othersRBS);
        othersRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        othersRBS.setForeground(new java.awt.Color(204, 0, 0));
        othersRBS.setText("Others");

        groceriesRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(groceriesRBS);
        groceriesRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        groceriesRBS.setForeground(new java.awt.Color(204, 0, 0));
        groceriesRBS.setText("Groceries");

        travelRBS.setBackground(new java.awt.Color(255, 204, 204));
        SearchTabBG.add(travelRBS);
        travelRBS.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        travelRBS.setForeground(new java.awt.Color(204, 0, 0));
        travelRBS.setText("Travel");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodRBS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billsRBS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entRBS, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(71, 71, 71)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transportRBS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shoppingRBS, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groceriesRBS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(healthcareRBS, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(travelRBS)
                        .addComponent(othersRBS)))
                .addGap(62, 62, 62))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodRBS)
                    .addComponent(transportRBS)
                    .addComponent(healthcareRBS))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billsRBS)
                    .addComponent(groceriesRBS)
                    .addComponent(travelRBS))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entRBS)
                    .addComponent(shoppingRBS)
                    .addComponent(othersRBS))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        recordCTA.setBackground(new java.awt.Color(255, 204, 204));
        recordCTA.setColumns(20);
        recordCTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recordCTA.setRows(5);
        recordCTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(recordCTA);

        searchSBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchSBTN.setForeground(new java.awt.Color(204, 0, 0));
        searchSBTN.setText("View Records");
        searchSBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSBTNActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Choose category:");

        totalCBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalCBTN.setForeground(new java.awt.Color(204, 0, 0));
        totalCBTN.setText("Total Spent ");
        totalCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCBTNActionPerformed(evt);
            }
        });

        totalCTA.setBackground(new java.awt.Color(255, 204, 204));
        totalCTA.setColumns(20);
        totalCTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalCTA.setRows(5);
        totalCTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(totalCTA);

        resetCBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetCBTN.setForeground(new java.awt.Color(204, 0, 0));
        resetCBTN.setText("Reset");
        resetCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetCBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(searchSBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalCBTN)
                .addGap(120, 120, 120))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetCBTN)
                                .addGap(25, 25, 25)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(resetCBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchSBTN)
                            .addComponent(totalCBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(406, 406, 406))
        );

        viewExp.addTab("Search by Category", jPanel7);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));

        jLabel17.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Enter the ID to delete:");

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(204, 0, 0));
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBTN)
                .addGap(51, 51, 51))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(idDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBTN))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        viewExp.addTab("Delete", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(viewExp, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1858, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(viewExp, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1225, Short.MAX_VALUE))
        );

        exitBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 51, 51));
        exitBTN.setText("Exit App");
        exitBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Your Personal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel8)
                        .addGap(213, 213, 213)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "See you again!"); // To display popup after user clicked exit button
        System.exit(0); // To close the window
    }//GEN-LAST:event_exitBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        String id = idDTF.getText().trim();  //Get and clean the input ID (remove spaces before/after)

        if(id.isEmpty()){ // To check whether id fields is empty or not
            JOptionPane.showMessageDialog(null, "Please enter an ID "); //To display popup when idTF field is empty
            return;
        }

        boolean success = manager.deleteExpense(id); //To test whether id has been found in the list or not
        if(success){
            JOptionPane.showMessageDialog(null, "Expense with ID: " + id + "\n" + "deleted successfully.");
        }else{
            JOptionPane.showMessageDialog(null, "No expense found with id " + id);
        }
        idDTF.setText("");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void totalCBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCBTNActionPerformed
        // TODO add your handling code here:
        String selectedCategory = getSelectedCategoryTabSearch(); // Get from button group
        double total = manager.calculateTotalByCategory(selectedCategory);
        String formatted = String.format("%.2f", total);
        totalCTA.setText("RM " + formatted); // to display total expense based on category
    }//GEN-LAST:event_totalCBTNActionPerformed

    private void searchSBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSBTNActionPerformed

        String category = getSelectedCategoryTabSearch(); // Get category from method getSelectedCategoryTabSearch()

        if (category == null) { //If category is empty
            JOptionPane.showMessageDialog(null, "Please select a category."); // To display popup when category field is empty
            return;
        }

        List<Expense> filtered = manager.searchByCategory(category); 

        if (filtered.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No expenses found in category " + getSelectedCategoryTabSearch());
            recordCTA.setText("");
            totalCTA.setText("");
        } else {
            recordCTA.setText(""); // kosongkan dulu
            for (Expense e : filtered) {
                // Display record
                recordCTA.append("ID: " + e.getId() +
                    "\nDate: " + e.getDate() +
                    "\nCategory: " + e.getCategory() +
                    "\nAmount: RM" + e.getAmount() +
                    "\nDescription: " + e.getDescription() +
                    "\n" + "\n");
            }
        }
    }//GEN-LAST:event_searchSBTNActionPerformed

    private void resetEBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetEBTNActionPerformed
        // TODO add your handling code here:
        //To clear all fields for user to add another expense
        idTF.setText("");
        editDateTF.setText("");
        editAmountTF.setText("");
        editCategoryTF.setText("");
        editDescTF.setText("");
    }//GEN-LAST:event_resetEBTNActionPerformed

    private void searchEBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEBTNActionPerformed

        // TODO add your handling code here:
        String id = idTF.getText().trim();  // get the ID from text field
        Expense exp = manager.findById(id); // call your method to find expense

        if (exp != null) {
            // Expense found and display details in text fields and enable editing
            editDateTF.setText(exp.getDate());
            editCategoryTF.setText(exp.getCategory());
            editAmountTF.setText(String.valueOf(exp.getAmount()));
            editDescTF.setText(exp.getDescription());

            editDateTF.setEnabled(true);
            editCategoryTF.setEnabled(true);
            editAmountTF.setEnabled(true);
            editDescTF.setEnabled(true);
            saveBTN.setEnabled(true);
        } else {
            // Not found so display popup maessage notify user and disable editing fields
            JOptionPane.showMessageDialog(null, "Expense ID not found.");

            editDateTF.setText("");
            editCategoryTF.setText("");
            editAmountTF.setText("");
            editDescTF.setText("");

            editDateTF.setEnabled(false);
            editCategoryTF.setEnabled(false);
            editAmountTF.setEnabled(false);
            editDescTF.setEnabled(false);
            saveBTN.setEnabled(false);
        }
    }//GEN-LAST:event_searchEBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        String id = idTF.getText().trim();
        Expense exp = manager.findById(id); //call method from expense manager class

        if(exp != null){ 
            //Update expenses that entered by user
            exp.setDate(editDateTF.getText().trim());
            exp.setCategory(editCategoryTF.getText().trim());
            exp.setAmount(Double.parseDouble(editAmountTF.getText().trim()));
            exp.setDescription(editDescTF.getText().trim());

            try {
                double amount = Double.parseDouble(editAmountTF.getText().trim());
                exp.setAmount(amount);
                JOptionPane.showMessageDialog(null, "Nice! Budget updated successfully");

            } catch (NumberFormatException exNum){
                JOptionPane.showMessageDialog(null, "Invalid  id. Please enter a valid id");

            }
        }else{
            JOptionPane.showMessageDialog(null, "No matching expense to update");
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void summaryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBTNActionPerformed
        // TODO add your handling code here:
        String summary = manager.displayAllExpenses();
        viewTA.setText(summary);
        String total = manager.calculateTotal();
        moneyOutTA.setText(total);
    }//GEN-LAST:event_summaryBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
        //Reset all fields
        dateTF.setText("");
        btnGRP.clearSelection();
        amountTF.setText("");
        descTF.setText("");
        moneyOutTA.setText("");
    }//GEN-LAST:event_resetBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        
        // Generate ID for new expense (got from expense class)
        String id = manager.generateID();
        
        //Get user input from text fields
        String date = dateTF.getText();
        String category = getSelectedCategoryTabAdd();
        //Convert String to double
        double amount = Double.parseDouble(amountTF.getText());
        String description = descTF.getText();

        //Create a new expense with entered data from user
        Expense e = new Expense (id, date, category, amount, description); //
        
        //Popup message for confirmation that data has been added
        JOptionPane.showMessageDialog(null, "Expense added! Click Reset to enter another");
        
        //Add the new expense to the list
        manager.addExpense(e);
        
        //Save the updated list to a file name expense.txt
        manager.saveToFile("expenses.text");
        
        //Update view area with all expenses
        String summary = manager.displayAllExpenses();
        viewTA.setText(summary);
        
        //Update total money spent and display in moneyOutTA field
        String total = manager.calculateTotal();
        moneyOutTA.setText(total);
    }//GEN-LAST:event_addBTNActionPerformed

    private void shoppingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shoppingRBActionPerformed

    private void healthcareRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthcareRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healthcareRBActionPerformed

    private void transportRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportRBActionPerformed

    private void billsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billsRBActionPerformed

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void resetCBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetCBTNActionPerformed
        // TODO add your handling code here:
        // To clear all fields and button group
        SearchTabBG.clearSelection();
        recordCTA.setText("");
        totalCTA.setText("");
    }//GEN-LAST:event_resetCBTNActionPerformed
    
    // Method for select category for Tab Add
    private String getSelectedCategoryTabAdd() {
        if (foodRB.isSelected()) 
            return "Food & Drink";
        if (shoppingRB.isSelected()) 
            return "Shopping";
        if (transportRB.isSelected()) 
            return "Transport";
        if (billsRB.isSelected()) 
            return "Bills & Fees";
        if (healthcareRB.isSelected()) 
            return "Healthcare";
        if (entertainmentRB.isSelected()) 
            return "Entertainment";
        if (groceriesRB.isSelected()) 
            return "Groceries";
        if (travelRB.isSelected()) 
            return "Travel";
        if (othersRB.isSelected()) 
            return "Others";
        return null; //If there are no category clicked
    }
    
        // Method for select category for Tab Search By Category
    private String getSelectedCategoryTabSearch() {
        if (foodRBS.isSelected()) 
            return "Food & Drink";
        if (shoppingRBS.isSelected()) 
            return "Shopping";
        if (transportRBS.isSelected()) 
            return "Transport";
        if (billsRBS.isSelected()) 
            return "Bills & Fees";
        if (healthcareRBS.isSelected()) 
            return "Healthcare";
        if (entRBS.isSelected()) 
            return "Entertainment";
        if (groceriesRBS.isSelected()) 
            return "Groceries";
        if (travelRBS.isSelected()) 
            return "Travel";
        if (othersRBS.isSelected()) 
            return "Others";
        return null; // If there are no category clicked
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    java.awt.EventQueue.invokeLater(() -> {
        new ExpensesTrackerGUI().setVisible(true);
    });
}
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SearchTabBG;
    private javax.swing.JButton addBTN;
    private javax.swing.JTextField amountTF;
    private javax.swing.JRadioButton billsRB;
    private javax.swing.JRadioButton billsRBS;
    private javax.swing.ButtonGroup btnGRP;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextField descTF;
    private javax.swing.JTextField editAmountTF;
    private javax.swing.JTextField editCategoryTF;
    private javax.swing.JTextField editDateTF;
    private javax.swing.JTextField editDescTF;
    private javax.swing.JRadioButton entRBS;
    private javax.swing.JRadioButton entertainmentRB;
    private javax.swing.JButton exitBTN;
    private javax.swing.JRadioButton foodRB;
    private javax.swing.JRadioButton foodRBS;
    private javax.swing.JRadioButton groceriesRB;
    private javax.swing.JRadioButton groceriesRBS;
    private javax.swing.JRadioButton healthcareRB;
    private javax.swing.JRadioButton healthcareRBS;
    private javax.swing.JTextField idDTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea moneyOutTA;
    private javax.swing.JRadioButton othersRB;
    private javax.swing.JRadioButton othersRBS;
    private javax.swing.JTextArea recordCTA;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton resetCBTN;
    private javax.swing.JButton resetEBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchEBTN;
    private javax.swing.JButton searchSBTN;
    private javax.swing.JRadioButton shoppingRB;
    private javax.swing.JRadioButton shoppingRBS;
    private javax.swing.JButton summaryBTN;
    private javax.swing.JButton totalCBTN;
    private javax.swing.JTextArea totalCTA;
    private javax.swing.JRadioButton transportRB;
    private javax.swing.JRadioButton transportRBS;
    private javax.swing.JRadioButton travelRB;
    private javax.swing.JRadioButton travelRBS;
    private javax.swing.JTabbedPane viewExp;
    private javax.swing.JTextArea viewTA;
    // End of variables declaration//GEN-END:variables
}
